### ISSUE TITLE
Move `initialize` functions to constructors

### ISSUE THREAD

**Issue by mattldawson** [NCAR/photo-decomp#37]

**Comment by K20shores** [comment]
@mattldawson does this mean to move every function called initialize into a constructor, or only some of them? If so, is an example of what you're looking for something like what already exists in [src/radiative_transfer.F90](https://github.com/NCAR/photo-decomp/blob/f624a0bd672c5765cc6874848b409584c2e0dc29/src/radiative_transfer.F90#L62)?

**Comment by mattldawson** [comment]
yes, it should be all of them and the radiative transfer is a good example

**Comment by K20shores** [comment]
This was only temporarily closed as we were merging in code. There is still more work to do to rename all of the init functions
