### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by K20shores** [NCAR/photo-decomp#46]
To support the usability and extensibility of photo-decomp as a stand-alone plugin, we need to develop documentation. The documentation should provide a complete API reference, answer common FAQs, and show common use cases with examples. Further, the documentation should provide a high level overview of the entire system and crucial parts so that new users can understand how to improve the system.

From a development perspective, certain components will need to have the design fully described both pictorially and in written language for posterity. 

# External, User documentation
This is the documentation for potential users.
- We'd like it to look like the documentation for [xarray](https://docs.xarray.dev/en/latest/contributing.html#contributing-to-the-documentation) and [matplotlib](https://matplotlib.org/stable/index.html) because this style of documentation is common and very clean looking

# Internal, Developer documentation
- This should be kept in a filesystem internal to NCAR employees to keep track of detailed technical designs.

**Comment by K20shores** [comment]
# User-facing Documentation
I recommend we write all of the documentation in [reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html), if we can. This would allow the docs to be generated with [Sphinx](https://www.sphinx-doc.org/en/master/index.html).

## API Reference
As I understand it, we can write comments in the files themselves that would fully document each module and class. Sphinx would be able to read this and generate the API reference automatically.

## General usage and tutorials
In addition to the API, good documentation should include examples and answers to common questions. This means we will have to write a good portion of the documentation by hand. However, it would still be processed by Sphinx.

I propose we make a `docs` directory and star writing them there.

**Comment by mattldawson** [comment]
This sounds great to me. Does it make sense to host the documentation on GitHub-pages? Maybe we could create a template for the documentation and set up GitHub Actions to build the documentation and push it to github-pages (or somewhere else)? ([this repo](https://github.com/open-atmos/camp) does this if it helps as a reference)

I think there will be specific contributions that scientist-developers will make semi-regularly (new cross-section, quantum yield, and dose rate equations). Maybe we could have a section for these developers with instructions for how to add these.

**Comment by K20shores** [comment]
Extension for Sphinx for fortran [here](https://github.com/VACUMM/sphinx-fortran)
